Add Makefile to build images
skilld-labs/docker-frontend pull request #10
Opened 2017-03-21 18:51 UTC by andypost

This change makes easy to manually rebuild images

@todo We need to add ARGS

2017-04-14 18:42 UTC, andriyun commented on Makefile
> +TAGS = d7 latest omega_4_3 omega_4_4 zen
LABEL directive was not added to d7 Docker file

2017-04-14 18:42 UTC, andriyun commented on latest/Dockerfile
> +  org.label-schema.name="docker-php" \
wrong container name

2017-04-14 18:42 UTC, andriyun commented on omega_4_3/Dockerfile
> +  org.label-schema.name="docker-php" \
wrong container name

2017-04-14 18:42 UTC, andriyun commented on omega_4_4/Dockerfile
> +  org.label-schema.name="docker-php" \
wrong container name

2017-04-14 18:42 UTC, andriyun commented on zen/Dockerfile
> +  org.label-schema.name="docker-php" \
wrong container name

2017-04-14 18:48 UTC, andypost commented on Makefile
> +TAGS = d7 latest omega_4_3 omega_4_4 zen
ашчув

2017-04-14 20:20 UTC, andriyun commented
It works!
Great

2017-04-14 20:31 UTC, andriyun commented on d7/Dockerfile
> +  org.label-schema.name="docker-gulp" \
Why docker-gulp?
Regarding description on this page http://label-schema.org/rc1/#label-semantics
`Text description of the image. May contain up to 300 characters.`

2017-04-14 20:31 UTC, andriyun commented on latest/Dockerfile
> +  org.label-schema.name="docker-gulp" \
need proper descriprion

2017-04-14 20:31 UTC, andriyun commented on omega_4_3/Dockerfile
> +  org.label-schema.name="docker-gulp" \
need proper descriprion

2017-04-14 20:31 UTC, andriyun commented on omega_4_4/Dockerfile
> +  org.label-schema.name="docker-gulp" \
need proper descriprion

2017-04-14 20:31 UTC, andriyun commented on zen/Dockerfile
> +  org.label-schema.name="docker-gulp" \
need proper descriprion

2017-05-03 19:03 UTC, andriyun commented
Ok for me
can  be merged

2017-05-03 19:04 UTC, andypost commented
Does it needs reroll

2017-05-03 19:17 UTC, iberdinsky-skilld commented
maybe add steps to check here? i'n not sure we need to update hub images for testing

2017-05-18 14:23 UTC, andriyun commented on Makefile
> +all: build push
Related to flow described here #16 
Would be great don't push images before them could be tested.
* make (build images localy)
* some script or testing section 
* push image if checks passed

2017-05-18 14:24 UTC, andriyun requested changes
Need update Makefile related to flow what we are going to implement #16

2017-07-14 17:10 UTC, andypost commented on Makefile
> +all: build push
Any idea for testing? I think at least 2 goals in make file is enough so let's file separate PR for #16

2017-07-19 06:15 UTC, iberdinsky-skilld commented on Makefile
> +all: build push
https://github.com/skilld-labs/docker-frontend/issues/16#issuecomment-316282592

2017-08-06 01:18 UTC, andypost commented
That should be in long time ago, just to make rebuild easy
The process of rebuild is manual now, this is just a helper
So I merging it & let's discus #16

2017-08-06 01:18 UTC, merged