Package.json management added. Yarn included.
skilld-labs/docker-frontend pull request #13
Opened 2017-04-07 09:27 UTC by iberdinsky-skilld

# What that commit about:

We have several issues with current npm docker-frontend build:
- List of packages is hard fixed and unversioned.
    ```sh
    ENV NPM_PACKAGES "bower \
      breakpoint-sass \
      browser-sync \
      ... 
      typey \
      zen-grids"
    ```
- If we want to add any new module to any project we have to update docker-frontend repo and its docker hub. 
- Current build not uses package.json from project and not uses package.json from [Zen](https://github.com/skilld-labs/zen/blob/8.x-7.x/STARTERKIT/package.json)
- If we plan to move to bowerless projects and use only node modules this build became useless. 

# What has been done here?

- Npm changed to [Yarn](https://yarnpkg.com/en/). It anounced as npm on steroids. https://www.sitepoint.com/yarn-vs-npm/ It is faster, has a lot of packaging features. But main reason of yarn: I couldn't do next things with npm. Maybe anyone can. 
- Instead of hardfixed list i'm using:
  ```sh
  ADD https://raw.githubusercontent.com/skilld-labs/zen/8.x-7.x/STARTERKIT/package.json .
  ```
  It seems good to use last version of modules. And actual list.
- Once installed module uses yarn caching.
- If project's package.json has any different modules inside then docker-entrypoint it will add required on first run. next time it will use cache. 
```sh
//second run
$ n
yarn install v0.22.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.06s.
yarn run v0.22.0
$ "/work/node_modules/.bin/gulp"
[09:01:08] Using gulpfile /work/gulpfile.js
[09:01:08] Starting 'clean:css'...
[09:01:08] Starting 'clean:styleguide'...
``` 
- Build not uses docker-frontend:latest now and became standalone for testing purposes.

# How to test?

1. `cd zen` 
2. `docker build -t front .`
3. `cd anyproject_theme` 
4. `alias n='docker run -p 3000:3000 -p 3001:3001 --rm -it -v $(pwd):/work front '` 
5. `n` 
6. If all ok add to anyproject_theme's package.json any new modules. Via npm, yarn or even copypaste from [that commit](https://github.com/xArturia/zen/blob/672784a95b44950e52965eb4195b8494ce03f046/STARTERKIT/package.json).
7. Repeat step 5) 

# Main thing here.

This is obviously not a final build. Just a mix of different ideas. Build became slower but smarter. Yarn has a lot of new [features](https://yarnpkg.com/en/docs/cli/). Or we can find similar on npm and make it work. Anyway we have a lot of space to make it faster. Please test it well. Thanks

2017-04-07 10:04 UTC, iberdinsky-skilld commented
#Another important thing here

We dont need all devDependencies in most cases of compile. so we need to have -production for installation devDependencies only on frontend developers machines. in all other cases build should be easier.

2017-05-03 18:30 UTC, andriyun commented
Need resolve conflicts before reivew

2017-06-30 16:59 UTC, pabloguerino requested changes

2017-06-30 16:59 UTC, pabloguerino commented on zen/Dockerfile
> +  curl -sL https://yarnpkg.com/latest.tar.gz | tar xz -C /opt && \
Seems like we already have `npm` here, so better to install yarn using npm instead

2017-06-30 19:11 UTC, andypost requested changes
This needs rework because image gets toooo much layesr & huge size because of build tools and temporary files

2017-06-30 19:11 UTC, andypost commented on zen/Dockerfile
> +RUN apk add --no-cache make g++ python git
Any reason for build tools? Later they are not installed

2017-06-30 19:11 UTC, andypost commented on zen/Dockerfile
> +RUN rm package.json
please join the lines to minimize docker layers

2017-06-30 19:11 UTC, andypost commented on zen/docker-entrypoint.sh
> +yarn install --check-files --ignore-optional --ignore-platform --cache-folder /opt/.yarn-cache
very bad idea to call install in entrypoint

2017-06-30 19:11 UTC, andypost commented on zen/Dockerfile
> +  apk del --purge curl
you need to remove build tools, they are no longer needed for gulp-sass

also you need to clean-up temporary files, see https://github.com/skilld-labs/docker-frontend/pull/20

2017-06-30 19:15 UTC, andypost commented
Also better to create separate image (and docker tag) for this image, see #20

2017-09-07 06:07 UTC, iberdinsky-skilld commented
this PR is pretty outdated now.

2017-09-07 06:07 UTC, closed without merging