Added susy docker.
skilld-labs/docker-frontend pull request #17
Opened 2017-06-26 08:12 UTC by hog-seruj

2017-06-26 08:24 UTC, andypost requested changes
needs polishing

2017-06-26 08:24 UTC, andypost commented on susy/Dockerfile
> +MAINTAINER Sergiy Borodulin
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

2017-06-26 08:24 UTC, andypost commented on susy/Dockerfile
> +ENV NPM_PACKAGES "susy"
It should be "`$NPM_PACKAGES` susy"

2017-06-26 08:24 UTC, andypost commented on susy/Dockerfile
> +  && apk del --purge make g++ python
This done in latest image, just add packages

2017-06-29 15:25 UTC, andypost approved these changes

2017-06-29 15:25 UTC, merged

2017-06-30 16:55 UTC, pabloguerino commented on susy/Dockerfile
> +  org.label-schema.description="Zen theme for Drupal - npm, gulp, bower, suzy & libsass" \
There is a typo in `susy`

2017-06-30 19:12 UTC, andypost commented on susy/Dockerfile
> +  org.label-schema.description="Zen theme for Drupal - npm, gulp, bower, suzy & libsass" \
thanx fixed!

2017-06-30 19:13 UTC, andypost commented on susy/Dockerfile
> +  org.label-schema.description="Zen theme for Drupal - npm, gulp, bower, suzy & libsass" \
I mean in https://github.com/skilld-labs/docker-frontend/pull/20