Drupal7 base theme (node-sass)
skilld-labs/docker-frontend pull request #8
Opened 2017-01-31 20:26 UTC by pabloguerino

This is for https://gitlab.the-s-team.com/Skilld/d7-base-theme

Example https://gitlab.the-s-team.com/Skilld/d7-base-theme#alternative-setup-docker

Everything works except `node-sass-asset-functions` (works outside docker) but this is something really simple, so maybe it's better to write our own as it won't take long and the logic isn't hard. This is required for the ruby/compass migration.

Will continue on this tomorrow, creating PR anyway as `node-sass-asset-functions` is not always required anyway, so the container can be used and the rest can be reviewed.

2017-02-01 16:59 UTC, Drintios commented
I'm getting issues trying to use this container on npm update i get:

```
+-- UNMET PEER DEPENDENCY webpack@>=1.3.0 <3

```
and also 

```
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! path /work/node_modules/gulp-eslint/node_modules/ansi-regex
npm ERR! code EXDEV
npm ERR! errno -18
npm ERR! syscall rename

npm ERR! EXDEV: cross-device link not permitted, rename '/work/node_modules/gulp-eslint/node_modules/ansi-regex' -> '/work/node_modules/ansi-regex'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /work/npm-debug.log
```

When trying to run gulp file i get 

```
/usr/bin/docker-entrypoint.sh: line 38: node-sass-glob: not found
module.js:472
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/work/gulpfile.js:16:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

2017-02-02 20:56 UTC, pabloguerino commented
### What has been fixed

fixed issues described in the PR (for yargs and sass-glob-node)

now checking up the issue with node-sass-asset-functions seems to me like it's a dependency issue.

yep, confirmed, dependency issue, now fixed.

added "&& apk del --purge make g++ python git" to keep the container small

so with this, container should be 100% finished, theme as well (maybe missing browsersync from Rafa, but not needed for humanis at least, migration can continue in the meanwhile)

-------------

### Testing

In order to test this changes, you can build up the container locally:

```
docker build -t anything/d7 d7 --no-cache
```

and run it inside the theme (d7-base-theme) it should compile without any errors

```
docker run --rm -it -v $(pwd):/work anything/d7
```

2017-02-03 16:23 UTC, andypost requested changes
Just few small nitpicks

2017-02-03 16:23 UTC, andypost commented on d7/Dockerfile
> +MAINTAINER Andy Postnikov
please remove, docker deprecated it

2017-02-03 16:23 UTC, andypost commented on d7/Dockerfile
> +    apk --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community add libsass && \
would be great to move `add` right after `apk`

2017-02-03 16:23 UTC, andypost commented on d7/Dockerfile
> +
no reason in extra line)

2017-02-03 16:23 UTC, andypost commented on d7/Dockerfile
> +COPY docker-entrypoint.sh /usr/bin/
better put it in `/usr/local/bin`

2017-02-03 16:45 UTC, pabloguerino commented
Updated! Thanks Andy for the review

2017-02-03 16:48 UTC, jbguerraz commented
LGTM

2017-02-04 09:21 UTC, andypost commented on d7/Dockerfile
> +CMD ["gulp"]
somehow there's no CR/LF now

2017-02-17 01:56 UTC, pabloguerino commented
Fixed crlf issue, tested container against a real project (the one that we tested the migration first) and it's all ok

2017-02-23 15:59 UTC, andypost approved these changes

2017-02-24 08:02 UTC, jbguerraz approved these changes
LGTM

2017-02-25 18:02 UTC, iberdinsky-skilld commented
getting errors in installation
`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.`
and
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/webpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN webpack-dev-server@2.4.1 requires a peer of webpack@^2.2.0 but none was installed.`

2017-02-25 18:06 UTC, Drintios commented
I think first one is related to second one and the second one is caused because fs event is required if you are using Mac but in case you don't, as it not supported on other platforms, it throws error, but nothing to worry about, I think this is a dependency for gulp, but as I wrote they include this in case you will use mac

2017-02-25 18:14 UTC, pabloguerino commented
what Rafa said it's correct, there is nothing to worry about that warning, just a message (not error) because of a dependency between different platforms that is not needed here and it's skipped

2017-03-01 15:07 UTC, merged

2017-03-01 15:52 UTC, andypost commented
It needs follow-up for local=>internal user mapping
Latest example https://github.com/tkyryliuk/drupal-boilerplate/blob/master/docker/web/entrypoint.sh#L8